# Generated by Django 3.2 on 2021-05-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gamer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='levelupapi.gamer'),
        ),
    ]
