# Generated by Django 3.2 on 2021-05-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0004_rename_name_game_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_type',
            new_name='gametype',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='difficulty',
            new_name='number_of_players',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='players',
            new_name='skill_level',
        ),
        migrations.AddField(
            model_name='game',
            name='maker',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
